plugins {
    alias(libs.plugins.tishina.android.library)
    // Hilt convention plugin already applies KSP — no separate `ksp` alias needed.
    alias(libs.plugins.tishina.android.hilt)
    alias(libs.plugins.tishina.jvm.testing)
    // Phase 5 — `OssLicensesParser` decodes `assets/oss_licenses.json` for the AboutScreen
    // licenses section (FR-21). A private `@Serializable` DTO is generated by this plugin
    // at compile-time and mapped into the domain `OssLicense` to keep `:core:domain` free
    // of serialization annotations.
    alias(libs.plugins.kotlin.serialization)
}

android {
    namespace = "ru.dmdp.tishina.core.data"

    defaultConfig {
        javaCompileOptions {
            annotationProcessorOptions {
                arguments["room.schemaLocation"] = "$projectDir/schemas"
            }
        }
    }

    sourceSets {
        // MigrationTestHelper reads `<canonicalName>/<version>.json` from `assets`. For
        // Robolectric-based unit tests we expose the exported schemas under test assets;
        // androidTest would normally pick the same directory up for real instrumentation.
        named("test") {
            assets.srcDirs("$projectDir/schemas")
        }
        named("androidTest") {
            assets.srcDirs("$projectDir/schemas")
        }
    }
}

ksp {
    arg("room.schemaLocation", "$projectDir/schemas")
    arg("room.incremental", "true")
}

dependencies {
    implementation(projects.core.domain)
    implementation(libs.kotlinx.coroutines.android)

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)

    // Phase 4 — DataStore-backed SettingsRepositoryImpl persists calibration, theme,
    // dynamic colors and locale. Lives in `:core:data` so Hilt can share the singleton
    // file with the rest of the data layer (Room DB + Settings under one storage root).
    implementation(libs.datastore.preferences)

    // Phase 5 — JSON decoder used by `OssLicensesParser` to convert
    // `assets/oss_licenses.json` into the domain `OssLicense` model.
    implementation(libs.kotlinx.serialization.json)

    testImplementation(projects.core.testing)
    testImplementation(libs.room.testing)
    testImplementation(libs.robolectric)
    // Robolectric ships JUnit 4 tests; vintage engine bridges them onto the JUnit 5 platform.
    testRuntimeOnly(libs.junit.vintage.engine)
}
